const FdcategoryDB = require("../schemas/Foodcategory")

// FdcategoryDB.create({
//     text:'美食',
//     imgUrl:'/image/meishi.png'
// })
// FdcategoryDB.create({
//     text:'生鲜果蔬',
//     imgUrl:'/image/guoshu.png'
// })
// FdcategoryDB.create({
//     text:'甜点饮品',
//     imgUrl:'/image/ice.png'
// })
// FdcategoryDB.create({
//     text:'鲜花蛋糕',
//     imgUrl:'/image/flower.png'
// })
// FdcategoryDB.create({
//     text:'美团专送',
//     imgUrl:'/image/kuaisong.png'
// })
// FdcategoryDB.create({
//     text:'夜宵',
//     imgUrl:'/image/yexiao.png'
// })
// FdcategoryDB.create({
//     text:'快餐简餐',
//     imgUrl:'/image/jiancan.png'
// })
// FdcategoryDB.create({
//     text:'异国料理',
//     imgUrl:'/image/liaoli.png'
// })
// FdcategoryDB.create({
//     text:'小吃馆',
//     imgUrl:'/image/xiaochi.png'
// })
// FdcategoryDB.create({
//     text:'家常菜',
//     imgUrl:'/image/jiachang.png'
// })