const shopDB = require("../schemas/shop")

shopDB.create({
    name:'华莱士全鸡汉堡',
    score:'4.8分',
    price:'人均￥20',
    sales:'月售1000',
    time:'30分钟',
    distance:'1.1km',
    message:'美团专送',
    pic:'/image/01.png'
})

shopDB.create({
    name:'华莱士全鸡汉堡',
    score:'4.8分',
    price:'人均￥20',
    sales:'月售1000',
    time:'30分钟',
    distance:'1.1km',
    message:'美团专送',
    pic:'/image/02.png'
})
shopDB.create({
    name:'华莱士全鸡汉堡',
    score:'4.8分',
    price:'人均￥20',
    sales:'月售1000',
    time:'30分钟',
    distance:'1.1km',
    message:'美团专送',
    pic:'/image/03.png'
})
shopDB.create({
    name:'华莱士全鸡汉堡',
    score:'4.8分',
    price:'人均￥20',
    sales:'月售1000',
    time:'30分钟',
    distance:'1.1km',
    message:'美团专送',
    pic:'/image/04.png'
})
shopDB.create({
    name:'华莱士全鸡汉堡',
    score:'4.8分',
    price:'人均￥20',
    sales:'月售1000',
    time:'30分钟',
    distance:'1.1km',
    message:'美团专送',
    pic:'/image/05.png'
})
shopDB.create({
    name:'华莱士全鸡汉堡',
    score:'4.8分',
    price:'人均￥20',
    sales:'月售1000',
    time:'30分钟',
    distance:'1.1km',
    message:'美团专送',
    pic:'/image/06.png'
})
shopDB.create({
    name:'华莱士全鸡汉堡',
    score:'4.8分',
    price:'人均￥20',
    sales:'月售1000',
    time:'30分钟',
    distance:'1.1km',
    message:'美团专送',
    pic:'/image/07.png'
})
shopDB.create({
    name:'华莱士全鸡汉堡',
    score:'4.8分',
    price:'人均￥20',
    sales:'月售1000',
    time:'30分钟',
    distance:'1.1km',
    message:'美团专送',
    pic:'/image/08.png'
})
shopDB.create({
    name:'华莱士全鸡汉堡',
    score:'4.8分',
    price:'人均￥20',
    sales:'月售1000',
    time:'30分钟',
    distance:'1.1km',
    message:'美团专送',
    pic:'/image/09.png'
})
shopDB.create({
    name:'华莱士全鸡汉堡',
    score:'4.8分',
    price:'人均￥20',
    sales:'月售1000',
    time:'30分钟',
    distance:'1.1km',
    message:'美团专送',
    pic:'/image/10.png'
})
shopDB.create({
    name:'华莱士全鸡汉堡',
    score:'4.8分',
    price:'人均￥20',
    sales:'月售1000',
    time:'30分钟',
    distance:'1.1km',
    message:'美团专送',
    pic:'/image/11.png'
})
shopDB.create({
    name:'华莱士全鸡汉堡',
    score:'4.8分',
    price:'人均￥20',
    sales:'月售1000',
    time:'30分钟',
    distance:'1.1km',
    message:'美团专送',
    pic:'/image/12.png'
})
shopDB.create({
    name:'华莱士全鸡汉堡',
    score:'4.8分',
    price:'人均￥20',
    sales:'月售1000',
    time:'30分钟',
    distance:'1.1km',
    message:'美团专送',
    pic:'/image/13.png'
})
shopDB.create({
    name:'华莱士全鸡汉堡',
    score:'4.8分',
    price:'人均￥20',
    sales:'月售1000',
    time:'30分钟',
    distance:'1.1km',
    message:'美团专送',
    pic:'/image/14.png'
})
shopDB.create({
    name:'华莱士全鸡汉堡',
    score:'4.8分',
    price:'人均￥20',
    sales:'月售1000',
    time:'30分钟',
    distance:'1.1km',
    message:'美团专送',
    pic:'/image/15.png'
})